name: Test+Deploy

on:
  push:
    branches:
      - main

jobs:

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v2
#      - run: yarn install
#      - run: yarn test

  deploy:
    runs-on: ubuntu-latest
#    needs: test
    environment: production
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@v3.1.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
